-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.submit_guess(
	_word character varying,
	_username character varying,
	_shortcode character varying)
    RETURNS SETOF correct_guess 
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1

AS $BODY$
declare
  word_id uuid := (select id from word where word = _word);
  room_id uuid := (select id from room where shortcode = _shortcode);
  _guess_id uuid;
begin

if word_id is null then return; end if;
if room_id is null then return; end if;

INSERT INTO guess (is_correct, username, room_id, word_id) VALUES (TRUE, _username, room_id, word_id) RETURNING id INTO _guess_id;

RETURN query SELECT * FROM correct_guess WHERE guess_id=_guess_id;

end;
$BODY$;

ALTER FUNCTION public.submit_guess(character varying, character varying, character varying)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.submit_guess(character varying, character varying, character varying) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.submit_guess(character varying, character varying, character varying) TO anon;

GRANT EXECUTE ON FUNCTION public.submit_guess(character varying, character varying, character varying) TO authenticated;

GRANT EXECUTE ON FUNCTION public.submit_guess(character varying, character varying, character varying) TO postgres;

GRANT EXECUTE ON FUNCTION public.submit_guess(character varying, character varying, character varying) TO service_role;
