-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE EXTENSION IF NOT EXISTS plv8;

CREATE OR REPLACE FUNCTION public.generate_shortcode(
	_length integer)
    RETURNS character varying
    LANGUAGE 'plv8'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
const validLetters = "acdefghjlmnpqrstuvwxyz2345679";
let shortcode;
while(!shortcode || plv8.execute("SELECT COUNT(*) FROM room WHERE shortcode = $1", [shortcode])[0].count > 0) {
  shortcode = "";
  for (let i = 0; i < _length; i++) {
    let randomNumber = Math.floor(Math.random() * validLetters.length);
    shortcode += validLetters.charAt(randomNumber);
  }
}
return shortcode;
$BODY$;

ALTER FUNCTION public.generate_shortcode(integer)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.generate_shortcode(integer) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.generate_shortcode(integer) TO anon;

GRANT EXECUTE ON FUNCTION public.generate_shortcode(integer) TO authenticated;

GRANT EXECUTE ON FUNCTION public.generate_shortcode(integer) TO postgres;

GRANT EXECUTE ON FUNCTION public.generate_shortcode(integer) TO service_role;
