-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.newest_puzzle_id(
	)
    RETURNS uuid
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
DECLARE
  puzzle_id uuid;
BEGIN
  SELECT id INTO puzzle_id FROM puzzle ORDER BY created_at DESC LIMIT 1;
  RETURN puzzle_id;
END;
$BODY$;

ALTER FUNCTION public.newest_puzzle_id()
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.newest_puzzle_id() TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.newest_puzzle_id() TO anon;

GRANT EXECUTE ON FUNCTION public.newest_puzzle_id() TO authenticated;

GRANT EXECUTE ON FUNCTION public.newest_puzzle_id() TO postgres;

GRANT EXECUTE ON FUNCTION public.newest_puzzle_id() TO service_role;

ALTER TABLE IF EXISTS public.room
    ALTER COLUMN puzzle_id SET DEFAULT newest_puzzle_id();
