INSERT INTO puzzle (date,outer_letters,center_letter,max_score)
VALUES ('2022-01-29','{"a","i","y","l","o","f"}','c',224);

INSERT INTO room (shortcode,name)
VALUES ('abcdef','Test Room');

INSERT INTO word (word,point_value,is_pangram,definition,part_of_speech,synonym)
VALUES
  ('callaloo',8,FALSE,NULL,NULL,NULL),
  ('acai',1,FALSE,NULL,NULL,NULL),
  ('focaccia',8,FALSE,NULL,NULL,NULL),
  ('cacao',5,FALSE,'tropical American tree producing cacao beans','noun','theobroma cacao'),
  ('calcify',7,FALSE,'become impregnated with calcium salts','verb',NULL),
  ('cloaca',6,FALSE,'a waste pipe that carries away sewage or surface water','noun','sewerage'),
  ('cool',1,FALSE,'great coolness and composure under strain','noun','sang-froid'),
  ('cocoa',5,FALSE,'a beverage made from cocoa powder and milk and sugar; usually drunk hot','noun','hot chocolate'),
  ('acacia',6,FALSE,'any of various spiny trees or shrubs of the genus Acacia','noun',NULL),
  ('calla',5,FALSE,'water arum','noun','genus calla'),
  ('calf',1,FALSE,'the muscular back part of the shank','noun','sura'),
  ('acyclic',7,FALSE,'having an open chain structure','adjective','open-chain'),
  ('cyclically',10,FALSE,NULL,NULL,NULL),
  ('ciao',1,FALSE,'an acknowledgment that can be used to say hello or goodbye (aloha is Hawaiian and ciao is Italian)','noun','aloha'),
  ('loci',1,FALSE,NULL,NULL,NULL),
  ('iliac',5,FALSE,'of or relating to the ilium','adjective',NULL),
  ('foci',1,FALSE,NULL,NULL,NULL),
  ('colic',5,FALSE,'acute abdominal pain (especially in infants)','noun','intestinal colic'),
  ('coil',1,FALSE,'a structure consisting of something wound in a continuous series of loops','noun','whorl'),
  ('cliff',5,FALSE,'a steep high face of rock','noun','drop-off'),
  ('calico',6,FALSE,'having sections or patches colored differently and usually brightly','adjective','varicoloured'),
  ('loco',1,FALSE,'informal or slang terms for mentally irregular','adjective','whacky'),
  ('icily',5,FALSE,'in a cold and icy manner',NULL,NULL),
  ('laic',1,FALSE,'characteristic of those who are not members of the clergy','adjective','secular'),
  ('laical',6,FALSE,NULL,NULL,NULL),
  ('coyly',5,FALSE,'in a coy manner',NULL,NULL),
  ('cola',1,FALSE,'carbonated drink flavored with extract from kola nuts (`dope'' is a southernism in the United States)','noun','dope'),
  ('local',5,FALSE,'anesthetic that numbs a particular area of the body','noun','topical anesthetic'),
  ('facial',6,FALSE,'cranial nerve that supplies facial muscles','noun','seventh cranial nerve'),
  ('official',8,FALSE,'conforming to set usage, procedure, or discipline','adjective','prescribed'),
  ('locally',7,FALSE,'to a restricted area of the body','adverb','topically'),
  ('cocci',5,FALSE,'any spherical or nearly spherical bacteria','noun','coccus'),
  ('cyclic',6,FALSE,'recurring in cycles','adjective','cyclical'),
  ('coolly',6,FALSE,'in a composed and unconcerned manner','adverb','nonchalantly'),
  ('call',1,FALSE,'assign a specified (usually proper) proper name to','verb','name'),
  ('facially',8,FALSE,'with respect to the face',NULL,NULL),
  ('focal',5,FALSE,'having or localized centrally at a focus','adjective',NULL),
  ('coif',1,FALSE,'the arrangement of the hair (especially a woman''s hair)','noun','hairstyle'),
  ('coal',1,FALSE,'burn to charcoal','verb','char'),
  ('coca',1,FALSE,'a South American shrub whose leaves are chewed by natives of the Andes; a source of cocaine','noun','erythroxylon coca'),
  ('lacy',1,FALSE,'made of or resembling lace','adjective','lacelike'),
  ('fallacy',7,FALSE,'a misconception resulting from incorrect reasoning','noun','false belief'),
  ('clay',1,FALSE,'the dead body of a human being','noun','stiff'),
  ('cloy',1,FALSE,'cause surfeit through excess though initially pleasing','verb','pall'),
  ('folic',5,FALSE,NULL,NULL,NULL),
  ('lilac',5,FALSE,'of a pale purple color','adjective','lilac-colored'),
  ('officially',17,TRUE,'with official authorization','adverb','formally'),
  ('cilia',5,FALSE,NULL,NULL,NULL),
  ('cyclical',8,FALSE,'recurring in cycles','adjective','cyclic');
