services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "${APP_PORT}:3000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: package*.json
        - action: rebuild
          path: Dockerfile.web
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    volumes:
      - cron_logs:/var/log/cron
    environment:
      - LOG_FILE_PATH=/var/log/cron
      - DATABASE_URL=${DATABASE_URL}
      - TZ="America/Chicago"
      - SCHEDULE_LOAD_PUZZLE="*/15 4-7 * * *" # Every 15 minutes between 4AM - 7AM
      - SCHEDULE_REMOVE_ROOMS="0 5 * * *" # 5 AM every day
      - PUZZLE_RETENTION_DAYS=3
      - ROOM_RETENTION_DAYS=7
      - PINO_LOG_LEVEL=debug
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  cron_logs:
