FROM node:26-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY ./scripts .

# Load puzzle and, if successful, remove puzzles older than 3 days
RUN echo "${SCHEDULE_LOAD_PUZZLE} npm run load-puzzle && npm run remove-puzzles ${PUZZLE_RETENTION_DAYS}" >> /etc/crontabs/root

# Remove rooms which have not been used in 7 days
RUN echo "${SCHEDULE_REMOVE_ROOMS} npm run remove-rooms ${ROOM_RETENTION_DAYS}" >> /etc/crontabs/root

CMD ["crond", "-f", "-l", "2"]