-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

DROP FUNCTION IF EXISTS public.submit_guess(_word character varying, _username character varying, _room_id uuid, _puzzle_id uuid);

CREATE OR REPLACE FUNCTION public.submit_guess(
	_word character varying,
	_username character varying,
	_room_id uuid)
    RETURNS SETOF correct_guess 
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE SECURITY DEFINER PARALLEL UNSAFE
    ROWS 1

    SET search_path=public
AS $BODY$
DECLARE
  word_id uuid := (SELECT id FROM word WHERE word = _word);
  _puzzle_id uuid := (SELECT puzzle_id FROM room WHERE id = _room_id);
  _guess_id uuid;
BEGIN

INSERT INTO guess (is_correct, username, room_id, puzzle_id, word_id) VALUES (TRUE, _username, _room_id, _puzzle_id, word_id) RETURNING id INTO _guess_id;

RETURN query SELECT * FROM correct_guess WHERE guess_id=_guess_id;

EXCEPTION 
  WHEN sqlstate '22P02' OR sqlstate '23503' OR sqlstate '23502' THEN 
    RETURN;

END;
$BODY$;

ALTER FUNCTION public.submit_guess(character varying, character varying, uuid)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.submit_guess(character varying, character varying, uuid) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.submit_guess(character varying, character varying, uuid) TO anon;

GRANT EXECUTE ON FUNCTION public.submit_guess(character varying, character varying, uuid) TO authenticated;

GRANT EXECUTE ON FUNCTION public.submit_guess(character varying, character varying, uuid) TO postgres;

GRANT EXECUTE ON FUNCTION public.submit_guess(character varying, character varying, uuid) TO service_role;
