-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

REVOKE ALL ON TABLE public.guess FROM anon;
REVOKE ALL ON TABLE public.guess FROM postgres;
REVOKE ALL ON TABLE public.guess FROM service_role;
GRANT ALL ON TABLE public.guess TO anon;

GRANT ALL ON TABLE public.guess TO service_role;

GRANT ALL ON TABLE public.guess TO postgres;
