-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.guess
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    is_correct boolean NOT NULL,
    username character varying COLLATE pg_catalog."default" NOT NULL,
    room_id uuid NOT NULL,
    word_id uuid,
    CONSTRAINT guess_pkey PRIMARY KEY (id),
    CONSTRAINT guess_room_id_fkey FOREIGN KEY (room_id)
        REFERENCES public.room (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT guess_word_id_fkey FOREIGN KEY (word_id)
        REFERENCES public.word (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.guess
    OWNER to postgres;

ALTER TABLE IF EXISTS public.guess
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.guess TO anon;

GRANT ALL ON TABLE public.guess TO authenticated;

GRANT ALL ON TABLE public.guess TO postgres;

GRANT ALL ON TABLE public.guess TO service_role;
