-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE VIEW public.newest_puzzle
 AS
 SELECT puzzle.id,
    puzzle.created_at,
    puzzle.date,
    puzzle.outer_letters,
    puzzle.center_letter,
    puzzle.max_score
   FROM puzzle
  ORDER BY puzzle.date DESC;

ALTER TABLE public.newest_puzzle
    OWNER TO postgres;

GRANT ALL ON TABLE public.newest_puzzle TO authenticated;
GRANT ALL ON TABLE public.newest_puzzle TO postgres;
GRANT ALL ON TABLE public.newest_puzzle TO anon;
GRANT ALL ON TABLE public.newest_puzzle TO service_role;
