-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.


ALTER TABLE public.room
    ALTER COLUMN shortcode TYPE character varying COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public.room
    ALTER COLUMN shortcode SET DEFAULT generate_shortcode(6);
ALTER TABLE IF EXISTS public.room
    ADD CONSTRAINT room_shortcode_key UNIQUE (shortcode);

ALTER TABLE IF EXISTS public.room
    ALTER COLUMN shortcode SET STORAGE EXTENDED;
