-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.submit_guess(
	_word character varying,
	_username character varying,
	_room_id uuid)
    RETURNS SETOF guess 
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1

AS $BODY$


declare
  word_id uuid := (select id from word where word = _word);
begin

if word_id is null then return; end if;

return query INSERT INTO guess (is_correct, username, room_id, word_id) VALUES (TRUE, _username, _room_id, word_id) returning *;

end;
$BODY$;

ALTER FUNCTION public.submit_guess(character varying, character varying, uuid)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.submit_guess(character varying, character varying, uuid) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.submit_guess(character varying, character varying, uuid) TO anon;

GRANT EXECUTE ON FUNCTION public.submit_guess(character varying, character varying, uuid) TO authenticated;

GRANT EXECUTE ON FUNCTION public.submit_guess(character varying, character varying, uuid) TO postgres;

GRANT EXECUTE ON FUNCTION public.submit_guess(character varying, character varying, uuid) TO service_role;
