-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE VIEW public.most_recent_correct_guess
 AS
 SELECT DISTINCT ON (room.id) room.id AS room_id,
    room.created_at AS room_created_at,
    correct_guess.created_at AS found_at,
    correct_guess.word_id,
    correct_guess.puzzle_id
   FROM correct_guess
     RIGHT JOIN room ON room.id = correct_guess.room_id;

ALTER TABLE public.most_recent_correct_guess
    OWNER TO postgres;

GRANT ALL ON TABLE public.most_recent_correct_guess TO authenticated;
GRANT ALL ON TABLE public.most_recent_correct_guess TO postgres;
GRANT ALL ON TABLE public.most_recent_correct_guess TO anon;
GRANT ALL ON TABLE public.most_recent_correct_guess TO service_role;
