-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.word
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    word character varying COLLATE pg_catalog."default" NOT NULL,
    point_value smallint NOT NULL,
    is_pangram boolean NOT NULL,
    definition text COLLATE pg_catalog."default",
    part_of_speech character varying COLLATE pg_catalog."default",
    synonym character varying COLLATE pg_catalog."default",
    CONSTRAINT word_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.word
    OWNER to postgres;

ALTER TABLE IF EXISTS public.word
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.word TO anon;

GRANT ALL ON TABLE public.word TO authenticated;

GRANT ALL ON TABLE public.word TO postgres;

GRANT ALL ON TABLE public.word TO service_role;

CREATE TABLE IF NOT EXISTS public.room
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    last_played timestamp with time zone NOT NULL DEFAULT now(),
    shortcode character varying COLLATE pg_catalog."default" NOT NULL,
    name character varying COLLATE pg_catalog."default",
    CONSTRAINT room_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.room
    OWNER to postgres;

ALTER TABLE IF EXISTS public.room
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.room TO anon;

GRANT ALL ON TABLE public.room TO authenticated;

GRANT ALL ON TABLE public.room TO postgres;

GRANT ALL ON TABLE public.room TO service_role;
